module.exports = {
  siteTitle: 'Oxy-Rehab Tlenoterapia Tychy', // <title>
  manifestName: 'Spectral',
  manifestShortName: 'Landing', // max 12 characters
  manifestStartUrl: '/',
  manifestBackgroundColor: '#663399',
  manifestThemeColor: '#663399',
  manifestDisplay: 'standalone',
  manifestIcon: 'src/assets/img/website-icon.png',
  // pathPrefix: '/tlenoterapia-tychy/', // This path is subpath of your hosting https://domain/portfolio
  pathPrefix: '',
  heading: 'Oxy-Rehab  ',
  subHeading: 'Zapraszamy na sesje tlenowe w Tychach ',
  explore: 'Dowiedz się więcej ',
  tekst1: 'Nasza komora hiperbaryczna wykorzystuje ciśnienie 1,3 ATA. Jest to nieiwazyjna metoda wprowadzania tlenu o stężeniu 93%, czyli o 30% wyższym niż ciśnienie atmosferyczne.',
  info1: 'Wzmocnij odporność swojego organizmu w naturalny sposób!',
  info11: 'Sesja w kapsule hiperbarycznej biostymuluje organizm, likwiduje zakażenia oraz odżywia niedotlenione komórki, a w rezultacie wzmacnia układ immunologiczny.',
  info2: 'Zyskaj wsparcie w trakcie aktualnej rehabilitacji',
  info22: 'Tlenoterapia hiperbaryczna wspiera proces aktualnie prowadzonych terapii i rehabilitacji. Działa przeciwzapalnie i przeciwbólowo. Likwiduje obrzęki.',
  info3: 'Jak działa tlenoterapia?',
  info33: 'Terapia tlenowa ma wszechstronny, pozytywny wpływ na nasze samopoczucie psychiczne i fizyczne. Pozwala zachować na dłużej młodość, dobre zdrowie, aktywuje siły witalne i odpornościowe',
  info4: 'Jak wygląda zabieg?' ,
  info40: 'Wchłanianie tlenu w wyższym ciśnieniu niż atmosferyczne jest wielokorotnie większe.',
  info41: ' Dlatego sesja w naszej komorze hiperbarycznej polega na podawaniu pacjentowi 93% tlenu w ciśnieniu 1.3 atmosfery przez 60- 80 minut',
  info44: [
    'aktywizacja komórek macierzystych,',
    'odbudowa systemu odpornościowego,',
    'tworzenie się nowych tkanek i naczyń krwionośnych,',
    'działanie baktrio- i wiurusobujcze,',
    'działanie przeciwbólowe i przeciwzapalne',
    'pobudzenie metabolizmu,',
      'regeneracja tkanki kostnej i mięśni szkieletowych,',
    'wzmożenie koncentracji i zapamiętywania',
      'wzrost sił życiowych',
  ],
  info5: 'Komora hiperbaryczna',
  info55: 'Bezpieczne urządzenie o miękkiej konstrukcji zapewnia komfortową pozycję siedzącą lub leżącą. Może pomieścić dwie osoby z możliwością indywidualnego natlenienia np. osobę dorosłą z dzieckiem.',
  //zastosowania
  zastosowania1: 'Kardiologia',
  zastosowania11: 'Korzystny wpływ na dolegliwości o charakterze wieńcowym. Zmniejsza nasilenie objawów niewydolności serca, zapobiega zawałom mięśnia sercowego, reguluje ciśnienie tętnicze.',
  zastosowania2: 'Ortopedia',
  zastosowania21: 'Poprawia przepływ krwi w uszkodzonych kończynach, zwiększa ciśnienie tlenu w kościach powodując ustępowanie stanu zapalnego kości i szpiku.',
  zastosowania3: 'Dermatologia',
  zastosowania31: 'Terapia ma zastosowanie w leczeniu trądziku, łuszczycy, atopowego zapalenia skóry, egzemy oraz trądziku różowatego. Redukuje wszelkie ogniska zapalne.',
  zastosowania4: 'Neurologia',
  zastosowania41: 'Ma zastosowanie w porażeniach mózgowych i pourazowych uszkodzeniach mózgu, powstałych w wyniku udaru lub wylewu. Ożywia i pobudza uśpione komórki, podnosi koncentrację.',
  zastosowania5: 'Stomatologia',
  zastosowania51: 'Pomaga w leczeniu ran po zabiegach chirurgicznych, poprawia ukrwienie w uszkodzonej tkance, stymuluje proces gojenia oraz skraca czas rekonwalescencji.',
  zastosowania6: 'Medycyna sportowa',
  zastosowania61: 'Podnosi wydolność fizyczną, przyspiesza procesy regeneracji tkanki mięśniowej, ścięgien i więzadeł. Działa przeciwbólowo, wpływa na procesy naprawcze w tkance kostnej.',
  zastosowania7: 'Medycyna estetyczna',
  zastosowania71: 'Działa stymulująco na fibroblasty, odpowiedzialne za syntezę kolagenu i elastyny, czyli włókien zapewniających elastyczność skórze.',
  zastosowania8: 'Onkologia',
  zastosowania81: 'Sprzyja rewitalizacji komórek i zapobiega dalszym uszkodzeniom. Oczyszcza organizm z toksyn i metali ciężkich, obniża poziom białka C-reaktywnego.',
  zastosowania9: 'Gastrologia',
  zastosowania91: 'Poprawia ukrwienie ścian jelit i redukuje ilość gazów jelitowych. Wspiera regenerację stanów zapalnych, np. jelita cienkiego, jelita grubego, trzustki. Zabija szkodliwe bakterie i wirusy.',
// kontakt
  kontakttel: '+48 516-555-597',
  kontaktul: ' ul. Legionów Polskich 40',
  kontaktty: ' 43-100 Tychy',
  kontaktmail: 'tlenoterapiatychy.tychy@gmail.com',

  // social
  socialLinks: [
    {
      style: 'brands',
      icon: 'fa-instagram',
      name: 'Instagram',
      url: 'https://www.instagram.com/tlenoterapia.tychy/',
    },
    {
      style: 'brands',
      icon: 'fa-facebook',
      name: 'Facebook',
      url: 'https://www.facebook.com/Tlenoterapiatychy',
    },
    {
      style: 'solid',
      icon: 'fa-envelope',
      name: 'Email',
      url: 'mailto: tlenoterapiatychy.tychy@gmail.com',
    },
  ],
};

//made by
